parser: '@typescript-eslint/parser'
settings:
  import/resolver: webpack
parserOptions:
  project: ./tsconfig.json
extends:
  - airbnb
  - plugin:@typescript-eslint/recommended
plugins:
  - '@typescript-eslint'
globals:
  document: true
  fetch: true
  FileReader: true
  window: true
  localStorage: true
  API_URL: true
rules:
  indent:
    - error
    - 4
    - SwitchCase: 0
  react/jsx-indent: ['error', 4]
  react/jsx-indent-props: ['error', 4]
  react/destructuring-assignment: off
  react/jsx-one-expression-per-line: off
  react/sort-comp: off
  react/no-array-index-key: off
  react/no-access-state-in-setstate: off
  react/no-did-update-set-state: off
  react/no-unescaped-entities: off
  radix: off
  no-shadow: off
  consistent-return: off
  prefer-destructuring: [1]
  max-len: ['error', 140]
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .tsx
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent':
    - error
    - 4
    - SwitchCase: 0
  '@typescript-eslint/no-explicit-any': off
